INSERT INTO public.license(name)
	VALUES ('DC Imperial Palace'),
	('DC Comics Bombshells'),
	('Dia De Los DC'),
	('Green Lantern'),
	('Harley Quinn'),
	('Hawkman'),
	('Peacemaker'),
	('Poison Ivy'),
	('Pops! With Purpose'),
	('Robin'),
	('Suicide Squad'),
	('Superman'),
	('The Flash'),
	('The Joker'),
	('Wonder Woman'),
	('Batman'),
	('Black Adam'),
	('Disney Villains'),
	('Five Nights At Freddy´s'),
	('Funko'),
	('Harry Potter'),
	('Jurassic World Dominion'),
	('Mickey Mouse'),
	('My Hero Academia'),
	('NBA'),
	('NFL'),
	('NHL'),
	('Naruto Shippuden'),
	('Pokémon'),
	('Star Wars'),
	('Stranger Things'),
	('The Mandalorian'),
	('The Nightmare Before Christmas'),
	('Aquaman'),
	('Catwoman'),
	('Avengers'),
	('Black Panther'),
	('Black Panther Wakanda Forever'),
	('Captain America'),
	('Deadpool'),
	('Doctor Strange'),
	('Doctor Strange In The Multiverse Of Madness'),
	('Hulk'),
	('Iron Man'),
	('Loki'),
	('Mech Strike'),
	('Moon Knight'),
	('Ms. Marvel'),
	('She-Hulk'),
	('Spider-Man'),
	('Thor'),
	('Thor Love And Thunder'),
	('What If'),
	('X-Men'),
	('Clone Wars'),
	('Obi-Wan Kenobi'),
	('Star Wars Concept Series'),
	('Star Wars Valentines'),
	('The Book Of Boba Fett'),
	('The Empire Strikes Back'),
	('The Rise Of Skywalker'),
	('Bob´s Burgers'),
	('Rick And Morty'),
	('South Park'),
	('The Simpsons'),
	('Attack On Titan'),
	('Avatar The Last Airbender'),
	('Black Clover'),
    ('Boruto: Naruto Next Generations'),
    ('Demon Slayer'),
    ('Dragon Ball Z'),
    ('Fairy Tail'),
    ('Fullmetal Alchemist'),
    ('Hello Kitty'),
    ('Hunter X Hunter'),
    ('Jujutsu Kaisen'),
    ('One Piece'),
    ('Samurai Jack'),
    ('Tokyo Ghoul'),
    ('Yu-Gi-Oh!'),
    ('Blue´s Clues'),
    ('Cow And Chicken'),
    ('G.I. Joe'),
    ('Hanna-Barbera'),
    ('Looney Tunes'),
    ('Masters Of The Universe'),
    ('Mighty Morphin Power Rangers'),
    ('Peanuts'),
    ('Powerpuff Girls'),
    ('Retro Toys'),
    ('Transformers'),
    ('Beauty And The Beast'),
    ('Cinderella'),
    ('Disney Archives'),
    ('Frozen'),
    ('Hocus Pocus'),
    ('Lightyear'),
    ('Maleficent'),
    ('Minnie Mouse'),
    ('Moana'),
    ('Peter Pan'),
    ('Pocahontas'),
    ('Sleeping Beauty'),
    ('Walt Disney World 50th'),
    ('Monsters Inc'),
    ('The Incredibles'),
    ('Toy Story'),
    ('Up'),
    ('WALL-E'),
    ('Apex Legends'),
    ('Assassins Creed'),
    ('Cuphead'),
    ('Fortnite'),
    ('Genshin Impact'),
    ('Halo'),
    ('Minecraft'),
    ('Overwatch'),
    ('Sally Face'),
    ('Sonic The Hedgehog'),
    ('Street Fighter'),
    ('The Last Of Us'),
    ('Tiny Tina´s Wonderlands'),
    ('Alien'),
    ('Bullet Train'),
    ('Dungeons And Dragons'),
    ('Free Guy'),
    ('Game Of Thrones'),
    ('Godzilla Vs Kong'),
    ('Hobbit'),
    ('House Of The Dragon'),
    ('Indiana Jones'),
    ('Jurassic Park'),
    ('Lord Of The Rings'),
    ('Squid Game'),
    ('The Matrix'),
    ('The Umbrella Academy'),
    ('ASPCA'),
    ('Back To The Future'),
    ('ET'),
    ('Footloose'),
    ('Godzilla'),
    ('Golden Girls'),
    ('Pops! With Purpose'),
    ('Star Trek'),
    ('The Godfather'),
    ('The Goonies'),
    ('The Sopranos'),
    ('The Warriors'),
    ('The Wizard Of Oz'),
    ('Zorro'),
    ('Elf'),
    ('Friends'),
    ('Ghostbusters'),
    ('Jingle All The Way'),
    ('Legally Blonde'),
    ('Letterkenny'),
    ('Luck'),
    ('Parks And Recreation'),
    ('Schitt´s Creek'),
    ('Seinfeld'),
    ('Ted Lasso'),
    ('The Office'),
    ('Who Framed Roger Rabbit'),
    ('Dr. Seuss'),
    ('Hamilton'),
    ('Rugrats'),
    ('Space Jam'),
    ('The Iron Giant'),
    ('The Proud Family'),
    ('A Nightmare On Elm Street'),
    ('Alien'),
    ('American Psycho'),
    ('Beetlejuice'),
    ('Bride Of Chucky'),
    ('Candyman'),
    ('Carrie'),
    ('Chucky'),
    ('Elvira'),
    ('Frankenstein'),
    ('Gremlins'),
    ('Halloween'),
    ('IT'),
    ('Jaws'),
    ('The Silence Of The Lambs'),
    ('The Texas Chainsaw Massacre'),
    ('Trick ‘R Treat'),
    ('Universal Monsters'),
    ('Bob´s Big Boy'),
    ('Cap ´N Crunch'),
    ('Cheetos'),
    ('Coca-Cola'),
    ('Frosted Flakes'),
    ('General Mills'),
    ('Hershey´s'),
    ('Honey Smacks'),
    ('Jack In The Box'),
    ('Kaboom Cereal'),
    ('Kellogg´s'),
    ('Kraft'),
    ('Lucky Charms'),
    ('McDonald´s'),
    ('Mike And Ike'),
    ('Pan Am'),
    ('Tapatio'),
    ('The Flintstones'),
    ('American History'),
    ('Directors'),
    ('Elvira'),
    ('Jordan Peele'),
    ('Spike Lee'),
    ('Stan Lee'),
    ('AC/DC'),
    ('Aaliyah'),
    ('BTS'),
    ('Bella Poarch'),
    ('Guns N Roses'),
    ('H.E.R.'),
    ('Iron Maiden'),
    ('Jimi Hendrix'),
    ('Lil Wayne'),
    ('Mariah Carey'),
    ('Notorious B.I.G.'),
    ('Oasis'),
    ('Post Malone'),
    ('Queen'),
    ('RUN-DMC'),
    ('TLC'),
    ('Tupac Shakur'),
    ('U2'),
    ('Whitney Houston'),
    ('G.I. Joe'),
    ('Hasbro'),
    ('Teenage Mutant Ninja Turtles'),
    ('Transformers'),
    ('Boxing'),
    ('Formula One Team'),
    ('MLB'),
    ('NASCAR'),
    ('Soccer'),
    ('Tennis'),
    ('WWE'),
    ('Back In Stock'),
    ('Chance Of Chase'),
    ('Coming Soon'),
    ('New Releases'),
    ('Disney Holiday 2021'),
    ('Dr. Seuss'),
    ('ET'),
    ('Footloose'),
    ('Guardians Of The Galaxy'),
    ('Haunted Mansion'),
    ('DMX'),
    ('Notorious B.I.G.'),
    ('Outkast'),
    ('Snoop Dogg'),
    ('oo Hollow'),
    ('ClownSpy'),
    ('Kawaii Village'),
    ('Munchies'),
    ('Oddvocados'),
    ('Snapsies'),
    ('Soda Kats'),
    ('Soup Troop'),
    ('The Office'),
    ('Toilet Ninjas'),
    ('Alice In Wonderland'),
    ('Froot Loops'),
    ('Gamer Food'),
    ('Maleficent'),
    ('Snow White'),
    ('The Little Mermaid'),
    ('Ultimate Princess Collection'),
    ('101 Dalmatians'),
    ('Alien'),
    ('Bob Ross'),
    ('Child´s Play'),
    ('Frozen'),
    ('IT'),
    ('Rudolph');
	
SELECT * FROM license